filebeat.prospectors:
- input_type: log
  paths:
    - nginx_json_logs
  json.keys_under_root: true
  document_type: logs

output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "nginx_json_elastic_stack_example"
  template.enabled: true
  template.name: nginx_json
  template.path: "nginx_json_template.json"
  template.overwrite: true
  pipeline: nginx_json_pipeline
