filebeat.prospectors:
- input_type: log
  paths:
    - nginxplus_json_logs
  json.keys_under_root: true
  document_type: logs

output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "nginxplus_json_elastic_stack_example"
  template.enabled: true
  template.name: nginxplus_json_elastic_stack_example
  template.path: "nginxplus_json_template.json"
  template.overwrite: true
  pipeline: nginxplus_json_pipeline